### ISSUE TITLE
Javascript issue on the thankyou page

### ISSUE THREAD

**Issue by ifyio** [Financial-Times/next-signup#320] opened 2016-03-15 11:39 UTC
The following error is rendered in the chrome browser console

```
Uncaught TypeError: Cannot read property 'querySelectorAll' of null
```

**Comment by lc512k** [comment] 2016-03-23 10:25
duplicate of https://github.com/Financial-Times/next-signup/issues/216

**Closed by lc512k** 2016-03-23 10:25 UTC
Labels: low hanging fruit
