### ISSUE TITLE
Apologies Error Message when USA-Visa-Premium  subscription is made

### ISSUE THREAD

**Issue by bushraawan** [Financial-Times/next-signup#370] opened 2016-03-18 11:18 UTC
When a user tries to subscribe for:
Country: USA
CC Type: Visa 
Subscription: Premium
 
he gets the 'Aplogies....' error message.

The link i am using for testing:
https://next.ft.com/signup/?offerId=f5203c83-e824-523d-5ef2-766c162f8eba&term=annual&segID=400864&segmentID=1ee18acf-9ef8-4f19-57a0-df24a75a0411

user-email:b.awan277-forward@ftqa.org

No user record and no subscription record found in salesforce.

**Comment by lc512k** [comment] 2016-03-18 11:47
Caused by https://github.com/Financial-Times/next-signup/issues/373

**Comment by ifyio** [comment] 2016-03-18 14:58
This should be fixed now so closing it

**Closed by ifyio** 2016-03-18 14:58 UTC
